index:
    path: /
    controller: App\Controller\DefaultController::index

api_login_check:
    path: /login
#    path: /api/login_check
#
get_admin_univ:
    path: /univ
    controller: App\Controller\Admin\AdminController::univ